# Generated by Django 3.0.8 on 2020-08-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Email',
        ),
    ]
