# Generated by Django 3.0.8 on 2020-09-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200825_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category_story',
            field=models.CharField(default='Brisbane-Events', max_length=200),
        ),
    ]
