# Generated by Django 3.0.8 on 2020-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsstory_category_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category_story',
            field=models.CharField(default='', max_length=200),
        ),
    ]
